version: '3.8'
services:
  dev-db:
    container_name: pg_container
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dnjsqhwo@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD_DEV}
    ports:
      - '5055:80'
